# Form implementation generated from reading ui file '.\roady.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(715, 472)
        MainWindow.setFixedSize(715, 472)
        #MainWindow.setStyleSheet("background-image: url('roz.jpg'); background-position: center;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.departure_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.departure_label.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.departure_label.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.departure_label.setObjectName("departure_label")
        self.departure_city_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.departure_city_lineEdit.setGeometry(QtCore.QRect(160, 30, 131, 31))
        self.departure_city_lineEdit.setObjectName("departure_city_lineEdit")
        self.departure_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.departure_label_2.setGeometry(QtCore.QRect(360, 30, 131, 31))
        self.departure_label_2.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.departure_label_2.setObjectName("departure_label_2")
        self.destination_city_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.destination_city_lineEdit.setGeometry(QtCore.QRect(500, 30, 131, 31))
        self.destination_city_lineEdit.setObjectName("destination_city_lineEdit")
        self.with_returrn_radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.with_returrn_radioButton.setGeometry(QtCore.QRect(40, 89, 131, 31))
        self.with_returrn_radioButton.setStyleSheet("font: 12pt \"Segoe UI\";")
        self.with_returrn_radioButton.setObjectName("with_returrn_radioButton")
        self.currency_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.currency_comboBox.setGeometry(QtCore.QRect(210, 90, 111, 31))
        self.currency_comboBox.setStyleSheet("font: 14pt \"Segoe UI\";\n"
"font: 12pt \"Segoe UI\";")
        self.currency_comboBox.setObjectName("currency_comboBox")
        self.currency_comboBox.addItem("")
        self.currency_comboBox.addItem("")
        self.fuel_type_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.fuel_type_comboBox.setGeometry(QtCore.QRect(30, 140, 131, 41))
        self.fuel_type_comboBox.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.fuel_type_comboBox.setObjectName("fuel_type_comboBox")
        self.fuel_type_comboBox.addItem("")
        self.fuel_type_comboBox.addItem("")
        self.persons_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.persons_label.setGeometry(QtCore.QRect(30, 205, 111, 31))
        self.persons_label.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.persons_label.setObjectName("persons_label")
        self.number_of_persons_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.number_of_persons_lineEdit.setGeometry(QtCore.QRect(150, 200, 121, 31))
        self.number_of_persons_lineEdit.setObjectName("number_of_persons_lineEdit")
        self.consumption_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.consumption_lineEdit.setGeometry(QtCore.QRect(200, 270, 121, 31))
        self.consumption_lineEdit.setObjectName("consumption_lineEdit")
        self.consumption_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.consumption_label.setGeometry(QtCore.QRect(30, 270, 151, 31))
        self.consumption_label.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.consumption_label.setObjectName("consumption_label")
        self.calculate_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_btn.setGeometry(QtCore.QRect(470, 290, 151, 71))
        self.calculate_btn.setStyleSheet("font: 14pt \"Segoe UI\";")
        self.calculate_btn.setObjectName("calculate_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.departure_label.setText(_translate("MainWindow", "Departure"))
        self.departure_label_2.setText(_translate("MainWindow", "Destination"))
        self.with_returrn_radioButton.setText(_translate("MainWindow", "With Return"))
        self.currency_comboBox.setItemText(0, _translate("MainWindow", "RON"))
        self.currency_comboBox.setItemText(1, _translate("MainWindow", "EURO"))
        self.fuel_type_comboBox.setItemText(0, _translate("MainWindow", "Gas"))
        self.fuel_type_comboBox.setItemText(1, _translate("MainWindow", "Diesel"))
        self.persons_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Persons</p></body></html>"))
        self.consumption_label.setText(_translate("MainWindow", "Consumption"))
        self.calculate_btn.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

